apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.component }}
  ports:
  - port: {{ .Values.servic.port }}
    targetPort: {{ .Values.appPort }}
